version: "2"
services:
  jenkins:
    build:
      context: .
    image: unigainfo/jenkins
    user: root
    privileged: true
    expose:
      - "8080"
      - "50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "/my/jenkins_home:/var/jenkins_home"
    restart: always
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    expose:
      - "80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    restart: always
    environment:
      - VIRTUAL_HOST=jenkins.unigainfo.com
    networks:
      - "nginx_reverse_proxy"
    depends_on: 
      - "jenkins"