version: 2
services:
  jenkins:
    build:
      context: .
    image: unigainfo/jenkins
    user: root
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "/my/jenkins_home:/var/jenkins_home"